In [28]:
import numpy as np
import pandas as pd

In [29]:
df=pd.read_csv('customer.csv')

In [30]:
df.sample(5)

    age  gender   review education purchased
18   19    Male     Good    School        No
11   74    Male     Good        UG       Yes
16   59    Male     Poor        UG       Yes
48   39  Female     Good        UG       Yes
44   77  Female  Average        UG        No

In [31]:
df=df.iloc[:,2:] #taking only ordinal data

In [32]:
df.sample(5)

     review education purchased
15     Poor        UG        No
14     Poor        PG       Yes
30  Average        UG        No
8   Average        UG        No
6      Good    School        No

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [34]:
X_train.head()

     review education
24  Average        PG
34  Average    School
23     Good    School
16     Poor        UG
0   Average    School

In [35]:
y_train.sample()

7    Yes
Name: purchased, dtype: object

<h4>now we import ordinal encoder and make class/object of it</h4>

In [36]:
from sklearn.preprocessing import OrdinalEncoder

In [37]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [38]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [39]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [42]:
X_train = pd.DataFrame(
    X_train,
    columns=df.columns[:2]   
)
#pandas doesnot support 2d slicing

In [44]:
X_train.sample(5)

    review  education
28     0.0        2.0
21     1.0        1.0
17     0.0        2.0
9      1.0        1.0
32     2.0        2.0

In [45]:
 #use label encoding when working on target/output column

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
le=LabelEncoder()

In [48]:
le.fit(y_train)

LabelEncoder()

In [49]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [50]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [51]:
y_train

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [57]:
y_train=pd.DataFrame(y_train,columns=[df.columns[-1]])

In [59]:
y_train.sample()

    purchased
37          0